### PR TITLE
Rename sensor info columns

### PR DESCRIPTION
**Pull request by matthew-schultz**
Related issue #101

Rename columns in sensor_info table to match column names in scrape-util database for compatibility with Eileen's views.
- renamed units to unit
- renamed sensor_part to type
- renamed sensor_id to query_string
- renamed sensor_type to script_folder
   - update init_crontab to use script_folder

### CODE REVIEW

**Comment by matthew-schultz** [comment]
I think I'm going to add a few more commits for the same files to this PR to avoid conflicts including
- renaming reading table and columns
- reordering the sensor_info columns to match the production database

**Comment by carlosparadis** [comment]
@matthew-schultz  Regarding column renaming, I remember @eileenpeppard wanted to have some indication on the column names of lonoa that she could not modify arbitrarily. However, with her additional request to have all queries working, that conflicts. 

At the end of the day, did I understand right we won't rename the columns she can't edit?

**Comment by matthew-schultz** [comment]
@carlosparadis 

That's correct, so far we are not renaming the columns she can't edit.

**Comment by matthew-schultz** [comment]
Updating datatypes to match scrape-util database

Alter all timestamp fields to timestamp(6)
- reading - datetime, upload_timestamp
- sensor_info - last_updated_datetime
- error_log - datetime

Change datatypes of character varying fields to character varying(n)
- sensor_info - building, variable_name, unit, type, appliance, room, surface, sample_resolution, query_string, note
- reading - units

**Pull request merged**
